### ISSUE TITLE
Querying by department can retrieve the wrong class

### ISSUE THREAD

**Issue by rjames187** [DereC4/ut-grade-viewer#6]
Searching by department code can retrieve a class from the wrong department. I've noticed that this is particularly a problem with departments with only one character such as "I" (Informatics) and "E" (English). Below is a screenshot of a search for E 320 producing the grade distribution for ASE 320 as a result. 
![image](https://user-images.githubusercontent.com/84684031/236706018-c084395f-62fa-448d-8d55-0c6361f932e3.png)
I believe the problem might lie in lines 77 and 87 in main.js as seen in the screenshot below.
![image](https://user-images.githubusercontent.com/84684031/236706141-8193469b-e343-4fd2-b00b-41c998f3985d.png)
Notice how cData["Course Prefix"] calls the includes() method. If the values of cData are strings then this line of code is checking whether the given department code is a substring of the query. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes
"E" is a substring of "ASE" which may explain why an ASE class appears when the user searches for E.

**Comment by DereC4** [comment]
Oh yeah that's probably why

**Comment by DereC4** [comment]
Changing it to a direct comparison should probably fix it; weird i thought i did that but guess not. Thanks for finding

**Comment by DereC4** [comment]
![image](https://user-images.githubusercontent.com/53978637/236834376-e32c3fc6-295f-47f7-a586-0f9631c47b04.png)
Seems to work now; thanks for reporting

**Comment by DereC4** [comment]
double check for me if u have time but again, thanks 
(love the fractal pfp btw)

**Comment by rjames187** [comment]
Thanks!

As far as I can tell, the problem has been solved.

I think your project will be very useful to a lot of people. Keep up the good work!

**Comment by DereC4** [comment]
thank you kind person
