### ISSUE TITLE
Show a page views.

### ISSUE THREAD

**Issue by PresidentSam100** [DereC4/ut-grade-viewer#7]
I would like to see the number of views that this page gets whether daily, weekly, or all-time. Just some metrics to show the popular use. This site has helped me and many others on several levels and I would love to see it grow.

**Comment by DereC4** [comment]
fascinating, i'll consider it!!

**Comment by PresidentSam100** [comment]
For sure.
Legit this is actually an idea I've had for my own personal site that I never got around to doing, but I figured it would translate well here too LOL.

**Comment by DereC4** [comment]
oh right this was implemented
